import { FACE_ART, FACE_MOTION_PARTS, type FaceMotion } from "./luke-face-art";

/**
 * Luke's face. The artwork is drawn here rather than loaded, for the same reason
 * the provider marks are — the renderer stays asset-free and the face scales
 * with whatever holds it — and painted in `currentColor`, so one drawing serves
 * the notch and the menu bar alike.
 *
 * Both of its inputs are generated by `design/generate-brand-assets.mjs`, which
 * cuts the SVGs in `design/brand/` from the same table: the geometry arrives as
 * `luke-face-art.ts` and the motions as `styles/face-motion.css`. Nothing about
 * the face is decided in this file; it only says which parts a motion needs and
 * in what order they nest.
 */
export function LukeFace({ motion }: { motion: FaceMotion }): React.JSX.Element {
  const parts = FACE_MOTION_PARTS[motion];

  return (
    <svg
      className="luke-face"
      data-motion={motion}
      viewBox={FACE_ART.VIEW_BOX}
      aria-hidden="true"
      focusable="false"
    >
      {/* Two layers, because two is the deepest stack any motion uses: a head
          that bobs while it rocks, or hops while it squashes. They are always
          drawn, and a motion that needs only one simply leaves the outer one
          still. A CSS transform on a layer replaces a transform attribute on the
          same element, so the resting tilt has to be a group of its own. */}
      <g className="luke-face-layer luke-face-layer-2">
        <g className="luke-face-layer luke-face-layer-1">
          <g transform={FACE_ART.TILT}>
            <path
              d={FACE_ART.SMILE}
              fill="none"
              stroke="currentColor"
              strokeWidth={FACE_ART.STROKE_WIDTH}
              strokeLinecap="round"
              strokeLinejoin="round"
            />
            {parts.lids ? (
              /* Asleep: closed lids in place of the eyes, not eyes that happen
                 to be shut — a blink is a squeeze, and a lid is an arc. */
              <>
                <path
                  d={FACE_ART.LID.LEFT}
                  fill="none"
                  stroke="currentColor"
                  strokeWidth={FACE_ART.LID_WIDTH}
                  strokeLinecap="round"
                />
                <path
                  d={FACE_ART.LID.RIGHT}
                  fill="none"
                  stroke="currentColor"
                  strokeWidth={FACE_ART.LID_WIDTH}
                  strokeLinecap="round"
                />
              </>
            ) : (
              /* Ellipses rather than circles: blinking, squinting and widening
                 are all the radius moving, and an ellipse has nothing to
                 convert. Each is named so the wink can close one of them. */
              <>
                <ellipse
                  className="luke-face-eye luke-face-eye-left"
                  cx={FACE_ART.EYE_X.LEFT}
                  cy={FACE_ART.EYE_Y}
                  rx={FACE_ART.EYE_RADIUS}
                  ry={FACE_ART.EYE_RADIUS}
                  fill="currentColor"
                />
                <ellipse
                  className="luke-face-eye luke-face-eye-right"
                  cx={FACE_ART.EYE_X.RIGHT}
                  cy={FACE_ART.EYE_Y}
                  rx={FACE_ART.EYE_RADIUS}
                  ry={FACE_ART.EYE_RADIUS}
                  fill="currentColor"
                />
              </>
            )}
            {parts.brows ? (
              <g className="luke-face-brows">
                <path
                  d={FACE_ART.BROW.LEFT}
                  fill="none"
                  stroke="currentColor"
                  strokeWidth={FACE_ART.BROW_WIDTH}
                  strokeLinecap="round"
                />
                <path
                  d={FACE_ART.BROW.RIGHT}
                  fill="none"
                  stroke="currentColor"
                  strokeWidth={FACE_ART.BROW_WIDTH}
                  strokeLinecap="round"
                />
              </g>
            ) : null}
          </g>
        </g>
      </g>

      {/* Outside the layers, because the z's rise off the head rather than with
          it: they keep drifting while it breathes. */}
      {parts.sleepZ
        ? FACE_ART.SLEEP_Z.map((sleepZ, index) => (
            <g key={sleepZ.path} transform={`translate(${sleepZ.x} ${sleepZ.y})`}>
              <path
                className={`luke-face-z luke-face-z-${index + 1}`}
                d={sleepZ.path}
                fill="none"
                stroke="currentColor"
                strokeWidth={FACE_ART.SLEEP_Z_WIDTH}
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </g>
          ))
        : null}
    </svg>
  );
}
