// Generated by design/generate-brand-assets.mjs. Do not edit by hand: change the
// artwork parameters in that script and re-run it.
//
// The face the renderer draws, in the artwork's own canvas coordinates, and the
// vocabulary of things it can be doing. The motions themselves are @keyframes in
// styles/face-motion.css, generated from the same table.

/** Luke's face, on the 240x240 canvas every asset in design/brand/ is cut from. */
export const FACE_ART = {
  /** A square window centred on the face. Loud motions leave it, and may. */
  VIEW_BOX: "48 51 146 146",
  /**
   * The face cropped to itself, the way the static mark SVGs are cut. Only for
   * a mark that never moves: it is tight enough that any motion would leave it.
   */
  MARK_VIEW_BOX: "53.85 62.67 134.29 122.37",
  /** The head's resting tilt, about the point the motions pivot on. */
  TILT: "rotate(-8 120 124)",
  /** The capital-L nose, curling into the smile. */
  SMILE: "M 104 84 V 150 Q 104 164 118 164 Q 140 164 168 142",
  STROKE_WIDTH: 16,
  EYE_Y: 92,
  EYE_RADIUS: 12,
  EYE_X: { LEFT: 78, RIGHT: 162 },
  /** Drawn only by the motions that raise them. */
  BROW: { LEFT: "M 67.8 71 Q 78 65 88.2 71", RIGHT: "M 151.8 71 Q 162 65 172.2 71" },
  BROW_WIDTH: 5,
  /** Closed eyes, for a face that is asleep rather than blinking. */
  LID: { LEFT: "M 66 91.4 Q 78 101 90 91.4", RIGHT: "M 150 91.4 Q 162 101 174 91.4" },
  LID_WIDTH: 6,
  SLEEP_Z: [
    { x: 176, y: 62, path: "M 0 0 H 8 L 0 8 H 8" },
    { x: 190, y: 46, path: "M 0 0 H 11 L 0 11 H 11" },
    { x: 166, y: 44, path: "M 0 0 H 6 L 0 6 H 6" },
  ],
  SLEEP_Z_WIDTH: 3.5,
  /** The struck-through bubble a hushed face wears where the sleeper's z's rise. */
  HUSH_MARK: {
    transform: "translate(181 54)",
    bubble:
      "M -8 -11 H 8 A 7 7 0 0 1 15 -4 V 4 A 7 7 0 0 1 8 11 H -3 L -10 17 L -8 11 A 7 7 0 0 1 -15 4 V -4 A 7 7 0 0 1 -8 -11 Z",
    bar: "M -12 13 L 12 -13",
    width: 3.5,
  },
} as const;

/** Every motion the artwork defines, whether or not the app has a moment for it. */
export const FACE_MOTION = {
  TALKING: "talking",
  YES: "yes",
  ERROR: "error",
  REVIEWING: "reviewing",
  SUCCESS: "success",
  LISTENING: "listening",
  IDLE: "idle",
  NOTIFICATION: "notification",
  WINK: "wink",
  SLEEPING: "sleeping",
  HUSHED: "hushed",
  REFRESH: "refresh",
  BOOP: "boop",
  MONITORING: "monitoring",
  APPEAR: "appear",
  ATTENTION: "attention",
  FLOATING: "floating",
  HIDING: "hiding",
  FLYOFF: "flyoff",
  TEASE: "tease",
  WAITING: "waiting",
  SHIMMY: "shimmy",
  DIZZY: "dizzy",
  GLANCE: "glance",
} as const;

export type FaceMotion = (typeof FACE_MOTION)[keyof typeof FACE_MOTION];

/** One full cycle: how long a caller waits to see a motion out before moving on. */
export const FACE_MOTION_CYCLE_MS = {
  talking: 650,
  yes: 2200,
  error: 3000,
  reviewing: 4400,
  success: 2000,
  listening: 3600,
  idle: 4600,
  notification: 4000,
  wink: 4000,
  sleeping: 4800,
  hushed: 5200,
  refresh: 4500,
  boop: 3200,
  monitoring: 3600,
  appear: 4000,
  attention: 4500,
  floating: 4800,
  hiding: 5000,
  flyoff: 3000,
  tease: 4200,
  waiting: 2400,
  shimmy: 2600,
  dizzy: 3200,
  glance: 3400,
} as const satisfies Record<FaceMotion, number>;

/** What a motion needs drawn beyond the resting smile and eyes. */
export const FACE_MOTION_PARTS = {
  talking: { brows: false, lids: false, sleepZ: false, hushMark: false },
  yes: { brows: false, lids: false, sleepZ: false, hushMark: false },
  error: { brows: false, lids: false, sleepZ: false, hushMark: false },
  reviewing: { brows: false, lids: false, sleepZ: false, hushMark: false },
  success: { brows: false, lids: false, sleepZ: false, hushMark: false },
  listening: { brows: false, lids: false, sleepZ: false, hushMark: false },
  idle: { brows: false, lids: false, sleepZ: false, hushMark: false },
  notification: { brows: true, lids: false, sleepZ: false, hushMark: false },
  wink: { brows: false, lids: false, sleepZ: false, hushMark: false },
  sleeping: { brows: false, lids: true, sleepZ: true, hushMark: false },
  hushed: { brows: false, lids: false, sleepZ: false, hushMark: true },
  refresh: { brows: false, lids: false, sleepZ: false, hushMark: false },
  boop: { brows: false, lids: false, sleepZ: false, hushMark: false },
  monitoring: { brows: false, lids: false, sleepZ: false, hushMark: false },
  appear: { brows: false, lids: false, sleepZ: false, hushMark: false },
  attention: { brows: false, lids: false, sleepZ: false, hushMark: false },
  floating: { brows: false, lids: false, sleepZ: false, hushMark: false },
  hiding: { brows: false, lids: false, sleepZ: false, hushMark: false },
  flyoff: { brows: false, lids: false, sleepZ: false, hushMark: false },
  tease: { brows: true, lids: false, sleepZ: false, hushMark: false },
  waiting: { brows: false, lids: false, sleepZ: false, hushMark: false },
  shimmy: { brows: false, lids: false, sleepZ: false, hushMark: false },
  dizzy: { brows: false, lids: false, sleepZ: false, hushMark: false },
  glance: { brows: false, lids: false, sleepZ: false, hushMark: false },
} as const satisfies Record<
  FaceMotion,
  { brows: boolean; lids: boolean; sleepZ: boolean; hushMark: boolean }
>;
