import { FACE_ART, FACE_MOTION_PARTS, type FaceMotion } from "@sidecar/surface";

/**
 * What Luke is doing, if anything. No motion is the resting face itself: no
 * `data-motion` matches no generated rule, so nothing animates and the drawing
 * simply sits there. Stillness is drawn by not asking for anything, which is
 * why it costs neither an entry in the artwork table nor a paused animation.
 */
interface LukeFaceProps {
  motion?: FaceMotion;
  /** Set for the motions that say something for as long as it stays true. */
  repeat?: boolean;
}

/** Nothing beyond the smile and the eyes, which is what a still face draws. */
const RESTING_PARTS = { brows: false, lids: false, sleepZ: false } as const;

/** The monoline stroke every drawn line of the face shares. */
const STROKE = {
  fill: "none",
  stroke: "currentColor",
  strokeLinecap: "round",
} as const;

/** The paired parts are drawn per side, keyed the way the artwork names them. */
const SIDES = ["LEFT", "RIGHT"] as const;
/** Each eye is named so the wink's generated rule can close one of them. */
const EYE_CLASS = { LEFT: "luke-face-eye-left", RIGHT: "luke-face-eye-right" } as const;

/**
 * Luke's face. The artwork is drawn here rather than loaded, for the same reason
 * the provider marks are — the renderer stays asset-free and the face scales
 * with whatever holds it — and painted in `currentColor`, so it can take the
 * microphone's colour.
 *
 * Both of its inputs are generated by `design/generate-brand-assets.mjs`, which
 * cuts the SVGs in `design/brand/` from the same table: the geometry arrives as
 * `@sidecar/surface`'s `face-art.ts` and the motions as `styles/face-motion.css`. Nothing about
 * the face is decided in this file; it only says which parts a motion needs and
 * in what order they nest. `luke-face-part` marks everything the artwork moves,
 * which is what the wiring in base.css plays, pauses, and repeats as one set.
 */
export function LukeFace({ motion, repeat = false }: LukeFaceProps): React.JSX.Element {
  const parts = motion === undefined ? RESTING_PARTS : FACE_MOTION_PARTS[motion];

  return (
    <svg
      className="luke-face"
      data-motion={motion}
      data-repeat={String(repeat)}
      viewBox={FACE_ART.VIEW_BOX}
      aria-hidden="true"
      focusable="false"
    >
      {/* Two layers, because two is the deepest stack any motion uses: a head
          that bobs while it rocks, or hops while it squashes. They are always
          drawn, and a motion that needs only one simply leaves the outer one
          still. A CSS transform on a layer replaces a transform attribute on the
          same element, so the resting tilt has to be a group of its own. */}
      <g className="luke-face-part luke-face-layer luke-face-layer-2">
        <g className="luke-face-part luke-face-layer luke-face-layer-1">
          <g transform={FACE_ART.TILT}>
            <path
              d={FACE_ART.SMILE}
              {...STROKE}
              strokeWidth={FACE_ART.STROKE_WIDTH}
              strokeLinejoin="round"
            />
            {parts.lids
              ? /* Asleep: closed lids in place of the eyes, not eyes that happen
                   to be shut — a blink is a squeeze, and a lid is an arc. */
                SIDES.map((side) => (
                  <path
                    key={side}
                    d={FACE_ART.LID[side]}
                    {...STROKE}
                    strokeWidth={FACE_ART.LID_WIDTH}
                  />
                ))
              : /* Ellipses rather than circles: blinking, squinting and widening
                   are all the radius moving, and an ellipse has nothing to
                   convert. */
                SIDES.map((side) => (
                  <ellipse
                    key={side}
                    className={`luke-face-part luke-face-eye ${EYE_CLASS[side]}`}
                    cx={FACE_ART.EYE_X[side]}
                    cy={FACE_ART.EYE_Y}
                    rx={FACE_ART.EYE_RADIUS}
                    ry={FACE_ART.EYE_RADIUS}
                    fill="currentColor"
                  />
                ))}
            {parts.brows ? (
              <g className="luke-face-part luke-face-brows">
                {SIDES.map((side) => (
                  <path
                    key={side}
                    d={FACE_ART.BROW[side]}
                    {...STROKE}
                    strokeWidth={FACE_ART.BROW_WIDTH}
                  />
                ))}
              </g>
            ) : null}
          </g>
        </g>
      </g>

      {/* Outside the layers, because the z's rise off the head rather than with
          it: they keep drifting while it breathes. */}
      {parts.sleepZ
        ? FACE_ART.SLEEP_Z.map((sleepZ, index) => (
            <g key={sleepZ.path} transform={`translate(${sleepZ.x} ${sleepZ.y})`}>
              <path
                className={`luke-face-part luke-face-z luke-face-z-${index + 1}`}
                d={sleepZ.path}
                {...STROKE}
                strokeWidth={FACE_ART.SLEEP_Z_WIDTH}
                strokeLinejoin="round"
              />
            </g>
          ))
        : null}
    </svg>
  );
}
