/**
 * The runtime's vocabulary: the identities it keeps apart, the storage
 * contracts a durable owner of conversation state satisfies, the execution
 * seams a host composes over, and the records delegation keeps. Node-free by
 * construction, because packages below the runtime — realtime, hosted,
 * voice, devtrace, memory — import this door and not the barrel, which
 * reaches `node:fs` and croner.
 */

/**
 * What a scheduler hands back so the same schedule can be cancelled. A
 * browser answers with a number, Node with a timer object, and a test with
 * whatever it keys its own map by — so the handle is only ever handed back,
 * never read. One type at the bottom of the graph, so a schedule made in one
 * package is cancellable in another.
 */
export type ScheduledTimer = number | object;

/** One day in milliseconds, for every age, half-life, and lookback measured in days. */
export const DAY_MS = 24 * 60 * 60 * 1000;

export {
  CHILD_CLEANUP,
  CHILD_CONTEXT_MODE,
  CHILD_RUN_STATUS,
  CHILD_RUN_TERMINAL_STATUS,
  type ChildCleanup,
  type ChildCompletionRecord,
  type ChildContextMode,
  type ChildPolicyMetadata,
  type ChildRunRecord,
  type ChildRunStatus,
  type ChildSpawnReceipt,
  COMPLETION_DELIVERY_STATUS,
  type CompletionDeliveryStatus,
  childCompletionRecordFromWire,
  childRunRecordFromWire,
  completionIdFor,
  isChildCleanup,
  isChildContextMode,
  isChildRunStatus,
  isCompletionDeliveryStatus,
  isTerminalChildRunStatus,
} from "./child-records.js";
export {
  type AgentRuntime,
  type CheckpointFormat,
  CONTEXT_INPUT_KIND,
  type CompactionOptions,
  type ContextAssembly,
  type ContextBootstrap,
  type ContextEngine,
  type ContextInput,
  type ContextInputKind,
  type ContextLifecycle,
  type ContextMark,
  type ContextOpening,
  checkpointFormatFromTag,
  checkpointFormatTag,
  type EmbeddingAdapter,
  type EmbeddingBatch,
  type EmbeddingIdentity,
  isReasoningEffort,
  type MaybePromise,
  MODEL_FAILURE,
  MODEL_RESPONSE_OUTCOME,
  type ModelAdapter,
  type ModelAnswer,
  type ModelCapabilities,
  type ModelCapabilitiesAnswer,
  type ModelCompaction,
  type ModelFailure,
  type ModelIncomplete,
  type ModelRequestOptions,
  type ModelResponse,
  type ModelResponseOutcome,
  type ModelTokenCount,
  type ModelUsage,
  REASONING_EFFORT,
  type ReasoningEffort,
  RUN_END_REASON,
  RUNTIME_EVENT,
  type RunEndReason,
  type RuntimeCheckpoint,
  type RuntimeCompaction,
  type RuntimeEvent,
  type RuntimeEventKind,
  type RuntimeEventListener,
  type RuntimeIdentity,
  type RuntimeRun,
  type RuntimeRunEnd,
  type RuntimeRunRequest,
  sameCheckpointFormat,
  type ToolExecutionContext,
  type ToolExecutor,
  type ToolInvocation,
  type ToolResult,
  type ToolSchema,
} from "./execution.js";
export {
  type AgentId,
  agentId,
  agentIdOf,
  CONVERSATION_KIND,
  type ConversationKind,
  childAgentOf,
  childIdOf,
  childSessionKey,
  conversationKindOf,
  DEFAULT_AGENT_ID,
  decodeKeyComponent,
  encodeKeyComponent,
  isConversationKind,
  isIdentifier,
  isRunOrigin,
  MAIN_CONVERSATION_NAME,
  MAIN_SESSION_KEY,
  mainSessionKey,
  observedSessionKey,
  observedSessionRefOf,
  RUN_ORIGIN,
  type RunOrigin,
  type SessionKey,
  sessionKey,
  threadSessionKey,
} from "./identifiers.js";
export {
  ARCHIVE_ENCODING,
  ARCHIVE_REASON,
  type ArchiveEncoding,
  type ArchiveReason,
  COMPACTION_SOURCE,
  type CompactionBoundary,
  type CompactionSource,
  type ConversationRecord,
  conversationRecordFromWire,
  conversationRecordToWire,
  type HistoryAppendOutcome,
  type HistoryArchiveRecord,
  historyArchiveRecordFromWire,
  isArchiveEncoding,
  isArchiveReason,
  isCompactionSource,
  type StoredTranscriptEvent,
  TRANSCRIPT_EVENT_KIND,
  type TranscriptEvent,
} from "./storage.js";
