// Generated by design/generate-surface-shared.mjs. Do not edit by hand: change
// the tables in that script and re-run it.
//
// Millisecond mirrors of the CSS duration tokens in motion-tokens.css, from the
// same table. A main-process constant that waits on a CSS total names these
// rather than restating the numbers. Pixel sizes follow the same rule: the
// window and the drawing both name these, and the stylesheet spends the CSS
// variables emitted beside them.

export const MOTION_DURATION_MS = {
  FAST: 280,
  SHAPE: 460,
  EXIT: 90,
  QUICK: 140,
  HOVER: 70,
} as const;

export const MOTION_DELAY_MS = {
  EXPAND: 200,
  PEEK: 60,
  ROW_STAGGER: 32,
} as const;

/** How far a bubble floats off the display's top edge. CSS: `--bubble-lift`. */
export const BUBBLE_LIFT = 4;

/** Tallest caption block the window holds — sized past a whole spoken reply,
 * because the block grows to the words and nothing scrolls. CSS: `--caption-max`. */
export const VOICE_CAPTION_MAX_HEIGHT = 210;

/** One chip row of the session notice band. CSS: `--notice-size`. */
export const SESSION_NOTICE_HEIGHT = 26;

/** Chip rows the band may grow to before scrolling. CSS: `--notice-max-rows`. */
export const SESSION_NOTICE_MAX_ROWS = 3;

/** Expanded panel width. CSS: `--panel-width`. */
export const PANEL_WIDTH = 620;
