// Generated by design/generate-surface-shared.mjs. Do not edit by hand: change
// the tables in that script and re-run it.
//
// Millisecond mirrors of the CSS duration tokens in motion-tokens.css, from the
// same table. A main-process constant that waits on a CSS total names these
// rather than restating the numbers.

export const MOTION_DURATION_MS = {
  FAST: 280,
  SHAPE: 460,
  EXIT: 90,
  QUICK: 140,
  HOVER: 70,
} as const;

export const MOTION_DELAY_MS = {
  EXPAND: 200,
  PEEK: 60,
  ROW_STAGGER: 32,
} as const;
