// Generated by design/generate-surface-shared.mjs. Do not edit by hand: change
// the tables in that script and re-run it.
//
// Labels and urgency order for a session's display state. Both surfaces read
// these so the marketing mock cannot advertise a different sentence or a
// different top row than the product draws.

import { SESSION_STATE, type SessionState } from "./fixtures";

export const STATE_LABEL: Record<SessionState, string> = {
  [SESSION_STATE.WORKING]: "Working",
  [SESSION_STATE.ATTENTION]: "Needs you",
  [SESSION_STATE.COMPLETE]: "Complete",
  [SESSION_STATE.UNKNOWN]: "Idle",
};

/** The state order the surface reads top-down and the badge collapses to. */
export const STATE_PRIORITY: readonly SessionState[] = [
  SESSION_STATE.ATTENTION,
  SESSION_STATE.WORKING,
  SESSION_STATE.COMPLETE,
  SESSION_STATE.UNKNOWN,
];

/** Most urgent first, and within one state the one that moved most recently. */
export function compareSessionsByUrgency(
  left: { state: SessionState; observedAt: number },
  right: { state: SessionState; observedAt: number },
): number {
  return (
    STATE_PRIORITY.indexOf(left.state) - STATE_PRIORITY.indexOf(right.state) ||
    right.observedAt - left.observedAt
  );
}
