export {
  type ChunkingOptions,
  chunkMarkdown,
  DEFAULT_CHUNKING,
  hashText,
  type MemoryChunk,
} from "./chunking.js";
export {
  appendOnlyPromotion,
  applyConsolidationPlan,
  boundCandidateText,
  CANDIDATE_ORIGIN,
  CANDIDATE_SESSION_KIND,
  CANDIDATE_STATUS,
  type CandidateOrigin,
  type CandidateSeed,
  type CandidateSessionKind,
  type CandidateStatus,
  CONSOLIDATION_ACTION,
  CONSOLIDATION_DEFAULTS,
  CONSOLIDATION_PHASE,
  CONSOLIDATION_SYSTEM_PROMPT,
  CONVERSATION_PATH_PREFIX,
  type ConsolidationAction,
  type ConsolidationOperation,
  type ConsolidationPhase,
  type ConsolidationPlan,
  type ConsolidationResult,
  candidateFromSeed,
  candidateKeyFor,
  candidateSourceRef,
  candidatesDuplicate,
  conceptTags,
  consolidationJob,
  consolidationPrompt,
  conversationCandidatePath,
  DEEP_RANKING_WEIGHTS,
  type DeepRanking,
  DREAM_DIARY_SYSTEM_PROMPT,
  DREAMS_FILE,
  type DreamDiaryEntry,
  dreamDiaryEntry,
  ingestionQuery,
  isConsolidationCandidateEligible,
  isConversationCandidate,
  isPromotionOriginBlocked,
  lineageMarker,
  type MemoryCandidate,
  memoryCandidateFromWire,
  memoryEntries,
  parseConsolidationPlan,
  passesDeepGates,
  promotedCandidateKeys,
  promotedEntry,
  promotionMarker,
  promotionMarkerKey,
  type RankedCandidate,
  type RecallSignalResult,
  type RemReflection,
  rankCandidate,
  recallSignalSeeds,
  reinforceCandidate,
  removePromotedEntries,
  remReflections,
  selectDeepPromotions,
  validateConsolidationPlan,
} from "./consolidation.js";
export {
  type EmbeddingModelIdentity,
  type IndexedChunkWrite,
  type IndexedFileWrite,
  type IndexedSourceRecord,
  type KeywordHit,
  MEMORY_ORIGIN,
  MEMORY_SOURCE,
  type MemoryOrigin,
  type MemoryProvenance,
  type MemoryReadResult,
  type MemorySearchAnswer,
  type MemorySearchResult,
  type MemorySource,
  type VectorHit,
} from "./contracts.js";
export {
  EMBEDDING_PROVIDER_SELECTION,
  type EmbeddingProviderSelection,
  MEMORY_SEARCH_DEFAULTS,
  RECALL_DEFAULTS,
  RETRIEVAL_MODE,
  type RetrievalMode,
} from "./defaults.js";
export {
  alreadyFlushedForCompaction,
  dailyNotePathFor,
  failedHousekeeping,
  type HousekeepingPrompt,
  housekeepingCompleted,
  housekeepingFellShort,
  isAppendOnlyRewrite,
  isDailyNotePathForDay,
  localDayStamp,
  MEMORY_FLUSH_DEFAULTS,
  MEMORY_HOUSEKEEPING_KIND,
  MEMORY_HOUSEKEEPING_OUTCOME,
  type MemoryFlushAssessment,
  type MemoryHousekeepingKind,
  type MemoryHousekeepingOutcome,
  type MemoryHousekeepingResult,
  memoryFlushPrompt,
  memoryFlushThreshold,
  resetCapturePrompt,
  SILENT_REPLY_TOKEN,
  shouldRunMemoryFlush,
} from "./flush.js";
export {
  appendNotebookEntry,
  maximumNotebookEntryLength,
  NOTEBOOK_FILE,
  type NotebookFile,
  notebookEntryText,
  type ParsedNotebook,
  type ParsedNotebookEntry,
  parseNotebook,
  REMEMBERED_HEADING,
  removeNotebookEntry,
} from "./notebook-markdown.js";
export {
  bm25RankToScore,
  buildFtsQuery,
  datedNoteDay,
  decayedScore,
  defaultRankingOptions,
  type HybridRankingOptions,
  isEvergreenMemoryPath,
  mergeHybridResults,
  mmrRerank,
  selectHybridSearchResults,
} from "./ranking.js";
export {
  boundRecentTurns,
  ConversationRecall,
  type ConversationRecallOptions,
  conversationRunsRecall,
  hasRecallIntent,
  isMaintenanceEligibleConversation,
  isRecallEligibleConversation,
  RECALL_DECISION,
  RECALL_ELIGIBLE_KINDS,
  RECALL_STATUS,
  type RecallAsk,
  type RecallDecision,
  type RecallEligibilityInput,
  type RecallRecentTurn,
  type RecallResult,
  type RecallStatus,
  type RecallSubrun,
  resolveRecallEscalation,
  summarizeRecallReply,
  type TrustedMemoryLookup,
} from "./recall.js";
export {
  prepareForIngestion,
  RECALLED_CONTEXT_MARKER,
  REDACTED_TOKEN,
  type RedactionResult,
  redactSensitiveText,
  stripRecalledContext,
} from "./redaction.js";
export {
  boundNoteLine,
  type DedupedSeeds,
  dedupe,
  historyLineHash,
  type IngestibleHistoryLine,
  type IngestibleLine,
  INGESTION_SCORE,
  ingestibleLines,
  NOTE_LINE_MAX_CHARS,
  type NoteFile,
  noteSeeds,
  recentHistoryLines,
} from "./ingestion.js";
export {
  type ConsolidationSweepDependencies,
  type ConsolidationSweepReport,
  type ConsolidationSweepStore,
  DEEP_PATH,
  type DeepPath,
  type DeepRewriteDecision,
  decideDeepRewrite,
  NOTE_BUDGET_SHARE,
  runConsolidationSweep,
  type ToolFreeAsk,
} from "./sweep.js";
export { jaccardSimilarity, stripBullet, textSimilarity, tokenize } from "./tokenize.js";
export { cosineSimilarity, parseEmbedding, serializeEmbedding } from "./vectors.js";
export { type MemoryWatcher, type MemoryWatchOptions, watchMemoryFiles } from "./watch.js";
